parameters:
  - name: environment
    displayName: Name of the environment to deploy to
    type: string
  - name: region
    displayName: Name of the AWS region deploy to
    type: string

jobs:
  - job: plan
    displayName: Plan
    steps:
      - template: aws/iam/configure.yml@templates
      - template: terraform/plan.yml@templates
        parameters:
          artifactName: ${{ parameters.environment }}_${{ parameters.region }}
          planAdditionalCommandOptions: '-var-file="variables/${{ parameters.environment }}.${{ parameters.region }}.tfvars"'
          workspaceName: expensely-app-${{ parameters.environment }}

  - template: azure-devops/approve.yml@templates
    parameters:
      dependsOn: plan
      timeoutInMinutes: 60
      userToNotify: '[Expensely]\Expensely Team'

  - deployment: apply
    displayName: Apply
    dependsOn: approve
    environment: ${{ parameters.environment }}
    strategy:
      runOnce:
        deploy:
          steps:
            - download: none
            - template: aws/iam/configure.yml@templates
            - template: terraform/apply.yml@templates
              parameters:
                artifactName: ${{ parameters.environment }}_${{ parameters.region }}
