name: 1.0$(Rev:.r)
resources:
  repositories:
    - repository: templates
      type: github
      name: expensely/azure-devops-templates
      endpoint: Expensely

pool:
  vmImage: ubuntu-latest

trigger:
  batch: true
  branches:
    include:
      - "main"

pr:
  branches:
    include:
      - '*'

stages:
  - stage: preview
    displayName: Preview
    dependsOn: []
    variables:
      - template: variables/preview.ap-southeast-2.yml@templates
    jobs:
      - template: templates/release.environment.yml
        parameters:
          environment: ${{variables.ENVIRONMENT}}
          region: ${{variables.REGION}}

  - stage: production
    displayName: Production
    dependsOn: []
    variables:
      - template: variables/production.ap-southeast-2.yml@templates
    jobs:
      - template: templates/release.environment.yml
        parameters:
          environment: ${{variables.ENVIRONMENT}}
          region: ${{variables.REGION}}
